apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-configmap
dath:
  SMTP_HOST: "mailserver.human-connection"
  SMTP_PORT: "25"
  GRAPHQL_PORT: "4000"
  GRAPHQL_URI: "http://nitro-backend.human-connection:4000"
  NEO4J_URI: "bolt://nitro-neo4j.human-connection:7687"
  NEO4J_AUTH: "none"
  CLIENT_URI: "https://{{ .Values.domain }}"
  NEO4J_apoc_import_file_enabled: "true"
  NEO4J_dbms_memory_pagecache_size: "490M"
  NEO4J_dbms_memory_heap_max__size: "500M"
  NEO4J_dbms_memory_heap_initial__size: "500M"
  NEO4J_dbms_security_procedures_unrestricted: "algo.*,apoc.*"
  VERSION: "0.1.0"
  SENTRY_DSN_WEBAPP: ""
  SENTRY_DSN_BACKEND: ""
  COMMIT: ""
