apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-backend
spec:
  replicas: 1
  minReadySeconds: 15
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: "100%"
  selector:
    matchLabels:
      human-connection.org/selector: deployment-backend
  template:
    metadata:
      name: deployment-backend
      annotations:
        backup.velero.io/backup-volumes: uploads
      labels:
        human-connection.org/commit: {{ .Values.commit }}
        human-connection.org/selector: deployment-backend
    spec:
      containers:
      - name: backend
        image: humanconnection/nitro-backend:latest
        imagePullPolicy: {{ .Values.pullPolicy }}
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secrets
        # volumeMounts:
        #   - mountPath: /nitro-backend/public/uploads
        #     name: uploads
      # volumes:
      # - name: uploads
      #   persistentVolumeClaim:
      #     claimName: uploads-claim
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
