apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.supportEmail }}
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
