apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-webapp
spec:
  ports:
    - name: web
      port: 3000
      targetPort: 3000
  selector:
    human-connection.org/selector: deployment-webapp
