---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nitro-embed
  namespace: human-connection
spec:
  replicas: 1
  minReadySeconds: 15
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: "100%"
  selector:
    matchLabels:
      human-connection.org/selector: deployment-human-connection-embed
  template:
    metadata:
      labels:
        human-connection.org/commit: COMMIT
        human-connection.org/selector: deployment-human-connection-embed
      name: "nitro-embed"
    spec:
      containers:
        - name: nitro-embed
          image: humanconnection/nitro-embed:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: human-connection
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
