apiVersion: v1
kind: Service
metadata:
  name: nitro-embed
  namespace: human-connection
  labels:
    human-connection.org/selector: deployment-human-connection-embed
spec:
  ports:
    - name: web
      port: 3050
      targetPort: 3050
  selector:
    human-connection.org/selector: deployment-human-connection-embed
