apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nitro-web
  namespace: staging
spec:
  replicas: 2
  minReadySeconds: 15
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-staging-web
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-staging-web
      name: nitro-web
    spec:
      containers:
      - env:
        - name: COMMIT
          value: <WEBAPP_COMMIT>
        - name: HOST
          value: 0.0.0.0
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: staging-backend
              key: GRAPHQL_URI
        - name: MAPBOX_TOKEN
          valueFrom:
            configMapKeyRef:
              name: staging-web
              key: MAPBOX_TOKEN
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: staging
              key: JWT_SECRET
              optional: false
        image: humanconnection/nitro-web:latest
        name: web
        ports:
        - containerPort: 3000
        resources: {}
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
