---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: nitro-neo4j
    namespace: staging
  spec:
    replicas: 1
    strategy: {}
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-staging-neo4j
    template:
      metadata:
        labels:
          workload.user.cattle.io/workloadselector: deployment-staging-neo4j
        name: nitro-neo4j
      spec:
        containers:
        - name: nitro-db-migration-worker
          image: humanconnection/db-migration-worker:latest
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: db-migration-worker
          env:
          - name: COMMIT
            value: <BACKEND_COMMIT>
          volumeMounts:
          - name: secret-volume
            readOnly: false
            mountPath: /root/.ssh
          - name: mongo-export
            mountPath: /mongo-export/
        - name: nitro-neo4j
          image: humanconnection/neo4j:latest
          imagePullPolicy: Always
          env:
          - name: COMMIT
            value: <BACKEND_COMMIT>
          - name: NEO4J_apoc_import_file_enabled
            value: "true"
          - name: NEO4J_dbms_memory_pagecache_size
            value: 1G
          - name: NEO4J_dbms_memory_heap_max__size
            value: 1G
          - name: NEO4J_AUTH
            value: none
          - name: NEO4J_URI
            valueFrom:
              configMapKeyRef:
                name: staging-neo4j
                key: NEO4J_URI
          - name: NEO4J_USER
            valueFrom:
              configMapKeyRef:
                name: staging-neo4j
                key: NEO4J_USER
          - name: NEO4J_AUTH
            valueFrom:
              configMapKeyRef:
                name: staging-neo4j
                key: NEO4J_AUTH
          ports:
          - containerPort: 7687
          - containerPort: 7474
          volumeMounts:
            - mountPath: /data/
              name: neo4j-data
            - mountPath: /mongo-export/
              name: mongo-export
        volumes:
        - name: secret-volume
          secret:
            secretName: ssh-keys
            defaultMode: 0400
        - name: mongo-export
          persistentVolumeClaim:
            claimName: mongo-export-claim
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data-claim
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: neo4j-data-claim
    namespace: staging
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: mongo-export-claim
    namespace: staging
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
