apiVersion: v1
kind: ConfigMap
data:
  CLIENT_URI: "https://nitro-staging.human-connection.org"
  MAPBOX_TOKEN: pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.KZ8KK9l70omjXbEkkbHGsQ
metadata:
  name: staging-web
  namespace: staging
