language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
services:
  - docker
  - neo4j

install:
  - git submodule update --remote --merge
  - yarn global add cypress

before_install:
  - cd Nitro-Backend && docker-compose start
  - cd Nitro-Web && docker-compose start

script:
  - cypress run
