version: '3.7'

services:
  webapp:
    image: humanconnection/nitro-web:latest
    build: .
    ports:
      - 3000:3000
      - 8080:8080
    networks:
      - hc-network
    environment:
      - HOST=0.0.0.0
      - BACKEND_URL=http://backend:4000

networks:
  hc-network:
    name: hc-network

volumes:
  node_modules:
