---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: nitro-backend
    namespace: human-connection
  spec:
    template:
      spec:
        containers:
        - name: nitro-maintenance-worker
          image: humanconnection/maintenance-worker:latest
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: maintenance-worker
          volumeMounts:
          - name: secret-volume
            readOnly: false
            mountPath: /root/.ssh
          - name: uploads
            mountPath: /uploads/
        volumes:
        - name: secret-volume
          secret:
            secretName: ssh-keys
            defaultMode: 0400
