apiVersion: v1
kind: Service
metadata:
  name: nitro-web
  namespace: staging
  labels:
    workload.user.cattle.io/workloadselector: deployment-staging-web
spec:
  ports:
    - name: web
      protocol: "TCP"
      port: 3000
      targetPort: 3000
  selector:
    workload.user.cattle.io/workloadselector: deployment-staging-web
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}

