apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-maintenance
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    human-connection.org/selector: deployment-maintenance
