apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-neo4j
spec:
  ports:
  - name: bolt
    port: 7687
    targetPort: 7687
  - name: web
    port: 7474
    targetPort: 7474
  selector:
    human-connection.org/selector: deployment-neo4j
