apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-export-volume
  namespace: staging
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/shared/mongo-exports/
