apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-volume
  namespace: staging
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/shared/uploads/
