apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-backend
spec:
  replicas: 1
  minReadySeconds: 15
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: "100%"
  selector:
    matchLabels:
      human-connection.org/selector: deployment-backend
  template:
    metadata:
      name: deployment-backend
      annotations:
        backup.velero.io/backup-volumes: uploads
      labels:
        human-connection.org/commit: {{ .Values.commit }}
        human-connection.org/selector: deployment-backend
    spec:
      containers:
      - name: backend
        image: humanconnection/nitro-backend:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "{{ .Values.application.initializeCommand }}", "&&", "{{ .Values.application.migrationsCommand }}"]
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secrets
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /nitro-backend/public/uploads
            name: uploads
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-claim
status: {}
