apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maintenance
  namespace: human-connection
spec:
  replicas: 2
  minReadySeconds: 15
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      human-connection.org/selector: deployment-human-connection-nginx
  template:
    metadata:
      labels:
        human-connection.org/commit: COMMIT
        human-connection.org/selector: deployment-human-connection-nginx
      name: maintenance
    spec:
      containers:
        - name: web
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: human-connection
          env:
            - name: HOST
              value: 0.0.0.0
          image: humanconnection/maintenance:latest
          ports:
            - containerPort: 80
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
